from typing import TypedDict


class DemoGame(TypedDict):
    app_id: int
    name: str
    minutes: int
    recent: int
    days_ago: int | None
    achievements: tuple[int, int] | None
    tags: list[str]
    moods: list[str]
    favorite: bool


DEMO_GAMES: list[DemoGame] = [
    {
        "app_id": 1145360,
        "name": "Hades",
        "minutes": 3684,
        "recent": 176,
        "days_ago": 2,
        "achievements": (42, 49),
        "tags": ["动作", "Roguelike", "剧情"],
        "moods": ["热血", "专注"],
        "favorite": True,
    },
    {
        "app_id": 1086940,
        "name": "Baldur's Gate 3",
        "minutes": 2772,
        "recent": 94,
        "days_ago": 4,
        "achievements": (19, 54),
        "tags": ["RPG", "选择驱动", "组队"],
        "moods": ["沉浸", "探索"],
        "favorite": True,
    },
    {
        "app_id": 2379780,
        "name": "Balatro",
        "minutes": 726,
        "recent": 63,
        "days_ago": 1,
        "achievements": (11, 31),
        "tags": ["卡牌", "Roguelike", "策略"],
        "moods": ["轻松", "专注"],
        "favorite": False,
    },
    {
        "app_id": 1091500,
        "name": "Cyberpunk 2077",
        "minutes": 1668,
        "recent": 0,
        "days_ago": 148,
        "achievements": (18, 57),
        "tags": ["开放世界", "RPG", "剧情"],
        "moods": ["沉浸", "探索"],
        "favorite": False,
    },
    {
        "app_id": 1868140,
        "name": "DAVE THE DIVER",
        "minutes": 504,
        "recent": 0,
        "days_ago": 93,
        "achievements": (17, 43),
        "tags": ["冒险", "经营", "独立"],
        "moods": ["轻松", "探索"],
        "favorite": False,
    },
    {
        "app_id": 413150,
        "name": "Stardew Valley",
        "minutes": 10482,
        "recent": 0,
        "days_ago": 61,
        "achievements": (33, 40),
        "tags": ["种田", "生活模拟", "合作"],
        "moods": ["治愈", "轻松"],
        "favorite": True,
    },
    {
        "app_id": 646570,
        "name": "Slay the Spire",
        "minutes": 8706,
        "recent": 0,
        "days_ago": 205,
        "achievements": (38, 46),
        "tags": ["卡牌", "策略", "Roguelike"],
        "moods": ["专注", "挑战"],
        "favorite": True,
    },
    {
        "app_id": 620,
        "name": "Portal 2",
        "minutes": 1120,
        "recent": 0,
        "days_ago": 410,
        "achievements": (35, 51),
        "tags": ["解谜", "第一人称", "合作"],
        "moods": ["动脑", "幽默"],
        "favorite": True,
    },
    {
        "app_id": 1794680,
        "name": "Vampire Survivors",
        "minutes": 7890,
        "recent": 0,
        "days_ago": 238,
        "achievements": (176, 220),
        "tags": ["动作", "Roguelite", "休闲"],
        "moods": ["解压", "热血"],
        "favorite": False,
    },
    {
        "app_id": 632470,
        "name": "Disco Elysium",
        "minutes": 0,
        "recent": 0,
        "days_ago": None,
        "achievements": (0, 45),
        "tags": ["RPG", "推理", "剧情"],
        "moods": ["沉浸", "阅读"],
        "favorite": False,
    },
    {
        "app_id": 753640,
        "name": "Outer Wilds",
        "minutes": 0,
        "recent": 0,
        "days_ago": None,
        "achievements": (0, 31),
        "tags": ["探索", "解谜", "太空"],
        "moods": ["好奇", "沉浸"],
        "favorite": False,
    },
    {
        "app_id": 1205520,
        "name": "Pentiment",
        "minutes": 0,
        "recent": 0,
        "days_ago": None,
        "achievements": (0, 41),
        "tags": ["叙事", "历史", "推理"],
        "moods": ["阅读", "沉浸"],
        "favorite": False,
    },
    {
        "app_id": 1562430,
        "name": "DREDGE",
        "minutes": 0,
        "recent": 0,
        "days_ago": None,
        "achievements": (0, 40),
        "tags": ["钓鱼", "探索", "恐怖"],
        "moods": ["神秘", "轻松"],
        "favorite": False,
    },
    {
        "app_id": 367520,
        "name": "Hollow Knight",
        "minutes": 286,
        "recent": 0,
        "days_ago": 322,
        "achievements": (7, 63),
        "tags": ["类银河战士恶魔城", "动作", "探索"],
        "moods": ["挑战", "沉浸"],
        "favorite": False,
    },
]
